### ISSUE TITLE
Problem installing/using CMAR and CPAR algorithms

### ISSUE THREAD

**Issue by estevaog3** [ianjjohnson/arulesCBA#26] opened 2022-05-18 23:02 UTC
Hello, there!

I've successfully installed arulesCBA package from CRAN and run the `CBA` algorithm with the `iris` dataset. 
However, I'm getting the following error when trying to install CMAR and CPAR algorithms:
```
> install_LUCS_KDD_CMAR()
You are about to download and compile the LUCS-KDD Software Library implementations of the CMAR algorithms.
This requires a working installation of the Java JDK including java and javac.
Note: The algorithms are only free to use for **non-commercial purpose**!
For details see: https://cgi.csc.liv.ac.uk/~frans/KDD/Software/

Installing from: https://cgi.csc.liv.ac.uk/~frans/KDD/Software/CMAR/cmar.tgz 
trying URL 'https://cgi.csc.liv.ac.uk/~frans/KDD/Software/CMAR/cmar.tgz'
Content type 'application/x-gzip' length 108868 bytes (106 KB)
==================================================
downloaded 106 KB

to: /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/CMAR 
Compiling.
error: file not found: /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/CMAR/runCMAR.java
Usage: javac <options> <source files>
use --help for a list of possible options
Warning messages:
1: In file.copy(file.path(src, "runCMAR.java"), path) :
  problem copying /runCMAR.java to /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/CMAR/runCMAR.java: No such file or directory
2: In system(exe, intern = TRUE) :
  running command '/usr/bin/javac -cp /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/CMAR /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/CMAR/runCMAR.java' had status 2
> install_LUCS_KDD_CPAR()
You are about to download and compile the LUCS-KDD Software Library implementations of the CPAR algorithms.
This requires a working installation of the Java JDK including java and javac.
Note: The algorithms are only free to use for **non-commercial purpose**!
For details see: https://cgi.csc.liv.ac.uk/~frans/KDD/Software/

Installing from: https://cgi.csc.liv.ac.uk/~frans/KDD/Software/FOIL_PRM_CPAR/foilPrmCpar.tgz 
trying URL 'https://cgi.csc.liv.ac.uk/~frans/KDD/Software/FOIL_PRM_CPAR/foilPrmCpar.tgz'
Content type 'application/x-gzip' length 50522 bytes (49 KB)
==================================================
downloaded 49 KB

to: /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/FOIL_PRM_CPAR 
Compiling.
error: file not found: /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/FOIL_PRM_CPAR/runCPAR.java
Usage: javac <options> <source files>
use --help for a list of possible options
error: file not found: /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/FOIL_PRM_CPAR/runFOIL.java
Usage: javac <options> <source files>
use --help for a list of possible options
error: file not found: /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/FOIL_PRM_CPAR/runPRM.java
Usage: javac <options> <source files>
use --help for a list of possible options
Warning messages:
1: In file.copy(file.path(src, "runCPAR.java"), path) :
  problem copying /runCPAR.java to /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/FOIL_PRM_CPAR/runCPAR.java: No such file or directory
2: In file.copy(file.path(src, "runFOIL.java"), path) :
  problem copying /runFOIL.java to /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/FOIL_PRM_CPAR/runFOIL.java: No such file or directory
3: In file.copy(file.path(src, "runPRM.java"), path) :
  problem copying /runPRM.java to /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/FOIL_PRM_CPAR/runPRM.java: No such file or directory
4: In system(exe, intern = TRUE) :
  running command '/usr/bin/javac -cp /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/FOIL_PRM_CPAR /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/FOIL_PRM_CPAR/runCPAR.java' had status 2
5: In system(exe, intern = TRUE) :
  running command '/usr/bin/javac -cp /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/FOIL_PRM_CPAR /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/FOIL_PRM_CPAR/runFOIL.java' had status 2
6: In system(exe, intern = TRUE) :
  running command '/usr/bin/javac -cp /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/FOIL_PRM_CPAR /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/FOIL_PRM_CPAR/runPRM.java' had status 2
```

## What I've tried
I've simply copied those missing files from `arulesCBA/LUCS_KDD_java/` to their corresponding directories on my local machine. And then the installation worked:
```
> install_LUCS_KDD_CMAR()
LUCS-KDD CMAR is already installed.
Location: /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/CMAR
> install_LUCS_KDD_CPAR()
LUCS-KDD CPAR is already installed.
Location: /usr/local/lib/R/site-library/arulesCBA/LUCS_KDD/FOIL_PRM_CPAR
```

But, when I run the CMAR algorithm, I get the following error message:

```
> cl <- CMAR(class ~ ., dataset, support = .2, confidence = .8, verbose = TRUE)
LUCS-KDD: CMAR 
Call: /usr/bin/java  -cp /cloud/lib/x86_64-pc-linux-gnu-library/4.2/arulesCBA/LUCS_KDD/CMAR runCMAR -N2 -F/tmp/RtmpbMvQqz/filef32ff1967c.num -S20 -C80 

Error: Could not find or load main class runCMAR
Caused by: java.lang.ClassNotFoundException: runCMAR
Error in .LUCS_KDD(formula, trans, method = "CMAR", parameter = paste0("-S",  : 
  Error in call: /usr/bin/java  -cp /cloud/lib/x86_64-pc-linux-gnu-library/4.2/arulesCBA/LUCS_KDD/CMAR runCMAR -N2 -F/tmp/RtmpbMvQqz/filef32ff1967c.num -S20 -C80
In addition: Warning message:
In system(exe, intern = TRUE) :
  running command '/usr/bin/java  -cp /cloud/lib/x86_64-pc-linux-gnu-library/4.2/arulesCBA/LUCS_KDD/CMAR runCMAR -N2 -F/tmp/RtmpbMvQqz/filef32ff1967c.num -S20 -C80' had status 1
```

So I'd like to get some help on this issue.

**Comment by mhahsler** [comment] 2022-05-19 16:20
@estevaog3 I have confirmed the issues using the latest version of R. It looks like a timing issue with copying files. I will submit a fix asap.

@SavioSilas There seems to be an issue with your Java installation. You probably have multiple versions installed. The following link may help: https://cimentadaj.github.io/blog/2018-05-25-installing-rjava-on-windows-10/installing-rjava-on-windows-10/

**Comment by mhahsler** [comment] 2022-05-20 00:42
This should be fixed now.

**Closed by mhahsler** 2022-05-20 00:42 UTC
Labels: bug
