### ISSUE TITLE
cannot allocate vector of size x Gb

### ISSUE THREAD

**Issue by kliegr** [ianjjohnson/arulesCBA#4] opened 2017-02-13 16:23 UTC
When trying to use arulesCBA I keep running into error "cannot allocate vector of size x Gb"

Steps to replicate:

download http://kdd.ics.uci.edu/databases/kddcup99/kddcup.data_10_percent.gz and unpack as kddcup.data_10_percent

    trainFold <- utils::read.csv("kddcup.data_10_percent_corrected", header  = FALSE, nrows=1000)
    # the data file does not contain header row, set it manually
    names(trainFold) <- c("duration","protocol_type","service","flag","src_bytes","dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins","logged_in","lnum_compromised","lroot_shell","lsu_attempted","lnum_root","lnum_file_creations","lnum_shells","lnum_access_files","lnum_outbound_cmds","is_host_login","is_guest_login","count","srv_count","serror_rate","srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate","diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count","dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate","dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate","dst_host_rerror_rate","dst_host_srv_rerror_rate","label")
    trainFold <- as.data.frame(sapply(trainFold,as.factor))
    classifier <- CBA(trainFold, "label", supp = 0.01, conf=0.5)

Result

> Error: cannot allocate vector of size 3.7 Gb
In addition: Warning message:
In apriori(ds.mat, parameter = list(minlen = 2, supp = support,  :
  Mining stopped (time limit reached). Only patterns up to a length of 5 returned

Note that I am reading only 1000 rows from the dataset.

**Comment by ianjjohnson** [comment] 2017-02-13 18:48
This is caused by an excessively low support value. When lots of rules are mined, the rule-row match matrix gets very large. There are two ways to fix this:
1) Update to the development version of arulesCBA by installing through GitHub. The development version currently uses sparse matrices for rule matching, and is therefore much more efficient and works for your dataset. I've tested it as shown below and it works properly:
`trainFold <- utils::read.csv("kddcup.data_10_percent", header  = FALSE, nrows=1000)
# the data file does not contain header row, set it manually
names(trainFold) <- c("duration","protocol_type","service","flag","src_bytes","dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins","logged_in","lnum_compromised","lroot_shell","lsu_attempted","lnum_root","lnum_file_creations","lnum_shells","lnum_access_files","lnum_outbound_cmds","is_host_login","is_guest_login","count","srv_count","serror_rate","srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate","diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count","dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate","dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate","dst_host_rerror_rate","dst_host_srv_rerror_rate","label")
trainFold <- as.data.frame(sapply(trainFold,as.factor))
classifier <- CBA(label ~ ., trainFold, supp = 0.01, conf=0.5)
`

Note that the CBA interface has changed in the most recent development version to use a formula instead of a class label as input, so this code is slightly different than yours.

2) Lower the threshold for support and confidence so that the rule set that's generated isn't so massive. For example, try supp = 0.05 and conf = 0.9. This should help get things working while arulesCBA 1.0.3 is in development.

Hope this helps!
Ian

**Comment by ianjjohnson** [comment] 2017-02-13 18:49
This is fixed in development version 1.0.3, which will be released on CRAN as soon as it has been more thoroughly tested.

**Closed by ianjjohnson** 2017-02-13 18:49 UTC
